# -*- coding: utf-8 -*-
"""plastic object_classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ii1I08Y7WOf4Eiyr519hf2FI5GUm62PH
"""

# -----------------------------
# IMPORT & SETUP
# -----------------------------
import tensorflow as tf
from tensorflow.keras import layers, models
import numpy as np
import random
import os

# Seeds for reproducibility
random.seed(42)
np.random.seed(42)
tf.random.set_seed(42)
os.environ['TF_DETERMINISTIC_OPS'] = '1'

# Dataset parameters
DATASET_PATH = "/content/drive/MyDrive/Dataset"
IMG_SIZE = (224, 224)
BATCH_SIZE = 16

# -----------------------------
# LOAD DATASET
# -----------------------------
train_ds = tf.keras.utils.image_dataset_from_directory(
    DATASET_PATH,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    validation_split=0.2,
    subset="training",
    seed=42,
    label_mode='int'
)

val_ds = tf.keras.utils.image_dataset_from_directory(
    DATASET_PATH,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    validation_split=0.2,
    subset="validation",
    seed=42,
    label_mode='int'
)

class_names = train_ds.class_names
print("Classes:", class_names)

# -----------------------------
# DATASET OPTIMIZATION
# -----------------------------
AUTOTUNE = tf.data.AUTOTUNE
train_ds = train_ds.prefetch(AUTOTUNE)
val_ds = val_ds.prefetch(AUTOTUNE)

# -----------------------------
# BUILD MODEL
# -----------------------------
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input

model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(224,224,3)),
    tf.keras.layers.Lambda(preprocess_input),

    tf.keras.layers.Conv2D(16, (3,3), activation='relu'),
    tf.keras.layers.MaxPooling2D(),

    tf.keras.layers.Conv2D(32, (3,3), activation='relu'),
    tf.keras.layers.MaxPooling2D(),

    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(16, activation='relu'),
    tf.keras.layers.Dense(3, activation='softmax')
])

model.compile(
    optimizer='adam',
    loss=tf.keras.losses.SparseCategoricalCrossentropy(),
    metrics=['accuracy']
)

model.summary()

# -----------------------------
# TRAIN MODEL
# -----------------------------
EPOCHS = 15
history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=EPOCHS
)

# -----------------------------
# SAVE MODEL
# -----------------------------
model.save("/content/drive/MyDrive/plastic_classificationModel.h5")
print("Model saved successfully!")

from tensorflow.keras.preprocessing import image
import numpy as np
from tensorflow.keras.models import load_model
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input

# redefine after runtime reset
IMG_SIZE = (224, 224)

# Class names (same order as training)
class_names = ['black', 'colorful', 'transparent']

# Load model
model = load_model(
    "/content/drive/MyDrive/plastic_classificationModel.h5",
    custom_objects={"preprocess_input": preprocess_input}
)
print("Model loaded successfully!")

def predict_image(img_path):
    img = image.load_img(img_path, target_size=IMG_SIZE)
    img_arr = image.img_to_array(img)
    img_arr = np.expand_dims(img_arr, axis=0)

    pred = model.predict(img_arr)
    cls = np.argmax(pred)

    conveyor_belts = {
        "black": "Conveyor Belt A",
        "transparent": "Conveyor Belt B",
        "colorful": "Conveyor Belt C"
    }

    predicted_class = class_names[cls]

    print("Detected Object Type:", predicted_class)
    print("Confidence:", round(pred[0][cls] * 100, 2), "%")
    print("Send object to:", conveyor_belts[predicted_class])

from sklearn import metrics
predict_image("/img path")